[metadata]
version = 1
generated_at = "2026-01-08T06:09:47.631465+00:00"

[[dependency]]
name = "echo-real-server-v1"
actr_type = "echo-real-server-v1"
fingerprint = "service_semantic:0d0d204d724cafc1cb8fd5d6f68ca683d9f6546c6e70deab75781a2f4230a755"
cached_at = "2026-01-08T06:09:47.631462+00:00"

[[dependency.files]]
path = "echo-real-server-v1/echo.proto"
fingerprint = ""
