[metadata]
version = 1
generated_at = "2026-01-07T10:25:56.291925+00:00"

[[dependency]]
alias = "echo-real-server-v1"
actr_type = "acme+EchoService"
name = "echo-real-server-v1"
fingerprint = "service_semantic:0d0d204d724cafc1cb8fd5d6f68ca683d9f6546c6e70deab75781a2f4230a755"
cached_at = "2026-01-07T10:25:56.291925+00:00"
files= [{ path = "acme+EchoService/echo.proto", fingerprint = ""}]
