[metadata]
version = 1
generated_at = "2026-01-08T09:03:45.660713+00:00"

[[dependency]]
name = "echo-real-server-v1"
actr_type = "acme+EchoService"
fingerprint = "service_semantic:0d0d204d724cafc1cb8fd5d6f68ca683d9f6546c6e70deab75781a2f4230a755"
cached_at = "2026-01-08T09:03:45.660679+00:00"

[[dependency.files]]
path = "echo-real-server-v1/echo.proto"
fingerprint = ""
